# docker-compose.yml (en la raíz del proyecto)
version: '3.8'
services:
  # Servicio del Backend (API)
  app:
    # Le decimos que construya la imagen usando el Dockerfile de la carpeta 'server'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      # Mapeamos el puerto 3001 de tu máquina al puerto 3000 del contenedor.
      # Usamos 3001 para evitar conflictos con React, que usa el 3000.
      - "3001:3000"
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - postgres_db
    volumes:
      # Sincroniza tu código local del server con el del contenedor
      # para ver cambios sin tener que reconstruir la imagen.
      - ./server:/app
      # Excluimos node_modules para usar los que se instalaron dentro del contenedor.
      - /app/node_modules

  # Servicio de la Base de Datos
  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: